Cleanup and reorganization
mikelolasagasti/revelation pull request #54
Opened 2020-09-26 01:32 UTC by gpoo

This is a series of patches that clean unused code, as well as reorganization
in the data directory, which ends up reducing the directories and `Makefile.am`
files to process. Also, there is renaming of files to make them consistent with
the rest of files.

I have another branch to work on top of this (or whatever changes were needed)
to use meson as a built system.

2020-09-26 08:59 UTC, mikelolasagasti requested changes

2020-09-26 08:59 UTC, mikelolasagasti commented on README.md
> +# ![revelation-log] Revelation
log -> logo

2020-09-26 12:15 UTC, gpoo commented on README.md
> +# ![revelation-log] Revelation
Fixed.

2020-09-27 10:51 UTC, mikelolasagasti approved these changes

2020-09-27 10:51 UTC, merged